source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.0'
gem 'redis'
gem 'redis-namespace'

# Use sqlite3 as the database for Active Record
gem 'sqlite3'
gem 'sidekiq'

# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.0'

gem 'activeadmin', github: 'gregbell/active_admin'
gem 'omniauth'
gem 'omniauth-google-oauth2'
gem "omniauth-github"
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

gem 'unicorn-rails'

# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 1.2'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

# gem 'rb-readline' , '~> 0.4.2'

group :development, :test do
  gem 'rspec-rails'
   gem 'spork-rails'
  gem 'guard-spork'
  gem 'childprocess'
  gem 'guard-rspec'
  gem 'guard-livereload'
end

group :test do
  gem 'selenium-webdriver'
  gem 'capybara'
  gem 'factory_girl_rails'
end

gem 'rb-fsevent', :require => false if RUBY_PLATFORM =~ /darwin/i 

# Use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]
